// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Settimana6Giorno1.Data;

#nullable disable

namespace Settimana6Giorno1.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    [Migration("20250317143316_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Settimana6Giorno1.Models.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DataDiNascita")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1c0d0f2-3a7b-4f8d-9b6c-0e5e2d8c3f4a"),
                            Cognome = "Barberis",
                            DataDiNascita = new DateTime(2001, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "rachele.barberis@gmail.com",
                            Nome = "Rachele"
                        },
                        new
                        {
                            Id = new Guid("9d5e3b7c-2a4f-41d8-bf6c-7e8a1d9c0f2e"),
                            Cognome = "Braghin",
                            DataDiNascita = new DateTime(2000, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "silvia.braghin@gmail.com",
                            Nome = "Silvia"
                        },
                        new
                        {
                            Id = new Guid("e7f4a9d1-5b3c-489a-8f21-1c6d9e7f2b3a"),
                            Cognome = "Turiaci",
                            DataDiNascita = new DateTime(2000, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "vittorio.turiaci@gmail.com",
                            Nome = "Vittorio"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
